name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Use the version your app is targeting

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Deploy to CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2" # Adjust this to your AWS region
        run: |
          aws deploy create-deployment \
            --application-name CodeDeploy_PersonalSiteBackend \
            --deployment-group-name PersonalSiteBackend \
            --github-location repository=lmhseos/LucasHenryPortifilioSiteBackend,commitId=${{ github.sha }} \
            --region ${{ env.AWS_REGION }}
